name: Github actions test

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout master branch Github
       uses: actions/checkout@v2

     - name: Setup JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8  
  
     - name: Build Maven project
       run: mvn -B package --file pom.xml
      
     - name: target folder ls -a
       run: |
        cd target
        ls -a
     - name: Run cucumber tests
       uses: convictional/trigger-workflow-and-wait@v1.6.1
       with:
          owner: kartaly-e
          repo: cucumber-10-min
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: maven.yml
          ref: master
